name: Export to crowdin

on:
  workflow_dispatch:
jobs:
  exportToCrowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install scons markdown
          sudo apt update
          sudo apt install gettext
          sudo apt install translate-toolkit
      - name: Create add-on
        run: |
          scons
      - name: Create pot file
        run: |
          scons pot
      - name: Convert markdown to pot
        run: md2po -P readme.md 


      #- name: Commit and push
        #run: |
          #git config user.name github-actions
          #git config user.email github-actions@github.com
          #git add crowdin.yml
          #git commit -m "Update configuration to register ${{github.event.inputs.repo}}"
          #git branch -u origin/main
          #git pull
          #git push
      - name: Crowdin upload
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          source: ${{ github.event.repository.name }}.pot
          translation: ${{ github.event.repository.name }}/locale/%two_leters_code%/nvda.po
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ vars.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
